### ISSUE TITLE
tablet view skips sections

### ISSUE THREAD

**Issue by kbenoit** [koheiw/quanteda_landing#1]
notably, the excellent sliding banner, and the endorsement text.

**Comment by koheiw** [comment]
I assume it happening on iPad. My Android tablet/phone seems OK.

**Comment by kbenoit** [comment]
Yes, iPad with Safari, but I verified that Chrome on the iPad displays it as on the desktop OS.

**Comment by koheiw** [comment]
@kbenoit can you check how it looks on your iPad?
https://themes.gohugo.io/theme/hugo-universal-theme/

We could use https://www.browserstack.com, a bit expensive though.

**Comment by kbenoit** [comment]
The banner doesn't show up on iPad Safari, iOS 11.0.3. 
![img_0151](https://user-images.githubusercontent.com/2182246/31757695-ea6348d4-b4a1-11e7-8b4b-30d0cc83999c.PNG)

However, it does show up on my iPhone 7, running the same os.
![img_7213](https://user-images.githubusercontent.com/2182246/31757781-5a58634a-b4a2-11e7-9c47-4b35bb141d99.PNG)

**Comment by koheiw** [comment]
I filed an issue in the theme's website to find a clue. @amatsuo's iPad Safari had not problem with it, so I am suspecting something related to your device is the cause. Please clear cache etc. of your Safari and check again.

**Comment by kbenoit** [comment]
Could be my ad blocker…

I;’ll try it on another iPad.

K

On 19 Oct 2017, at 19:22, Kohei Watanabe <notifications@github.com<mailto:notifications@github.com>> wrote:


I filed an issue in the theme's website to find a clue. @amatsuo<https://github.com/amatsuo>'s iPad Safari had not problem with it, so I am suspecting something related to your device is the cause. Please clear cache etc. of your Safari and check again.

**Comment by kbenoit** [comment]
I've confirmed - it was an ad blocker I'd installed on my iPad. When I turn that off, it appears fine. All good now.
