### ISSUE TITLE
Offer workshops

### ISSUE THREAD

**Issue by stefan-mueller** [koheiw/quanteda_landing#11]
We realised that there is potential for more workshops at various institutions. I have created a sub-page with information for people who are interested in hosting a **quanteda** workshop (https://github.com/quanteda/quanteda_landing/tree/workshop). Please have a close look and feel free to make edits, @kbenoit and @koheiw.

**Comment by kbenoit** [comment]
Let's talk about this offline, since I get these requests about twice a month. I have a plan to offer this through the Quanteda Initiative, in a way that benefits everyone.

**Comment by stefan-mueller** [comment]
Excellent, good to hear that there is demand for more workshops! Yes, let’s talk about this offline. I close the issue for now.
