### ISSUE TITLE
Layout of "News" pages

### ISSUE THREAD

**Issue by stefan-mueller** [koheiw/quanteda_landing#15]
Two minor issues:

1. For some reason, the quanteda and QI logos at the top are not displayed properly for the "News" pages (see [here](https://quanteda.io/news/2018/01/28/workshop-at-wzb-2018/)). 
2. Under each news article we have a "discussion" box (which seems reasonable) and the "Also on Devcows" block which lists comments and posts from random pages not related to **quanteda** or text analysis. Is it possible to remove the Devcows box or is there any advantage of having it on the page?

**Comment by koheiw** [comment]
I fixed the first issue now. Good that you noticed that. I think **Devcow** is the user name of the guy who created the original template . We need to get our own API Key from DISQUS.
