### ISSUE TITLE
Add "Publications using quanteda" section

### ISSUE THREAD

**Issue by stefan-mueller** [koheiw/quanteda_landing#4]
If you're interested, I could check the citations for the **quanteda** package on Google Scholar once a month and create a list of published papers/books (not working papers) that use **quanteda** in their analysis.  We could make a sub-page called "References" or "Publications" on the landing page and offer authors to send us details about publications that are missing on the list.
Let me know if you think that's a good idea – happy to take care of this.

**Comment by koheiw** [comment]
I think this is a great idea, and we should have done this earlier.

**Comment by stefan-mueller** [comment]
Ok, two ways of how we could proceed: 

1. Create the bibliography manually as they do [here](http://www.comparativecandidates.org/node/5) for example.
2. Create a .bib file with the relevant references and update the list of references based on this file. Would something like [this](https://stackoverflow.com/a/46488860) work with the website? It seems that this solution requires. Rmd files, but the **quanteda** website is based on .md. If this option is not possible or too complicated, we go with option 1.

I would say that we add all published papers (no working papers) and books/book chapters and sort them by year. I could check Google Scholar once a month and add new publications.

**Comment by kbenoit** [comment]
Rather than try to maintain this, why not simply link to the [quanteda record on Google Scholar](https://scholar.google.co.uk/scholar?oi=bibs&hl=en&cites=4124149528480169545,5426967797859565261,10275772072778885251,5689866426931637102)?

Maintaining a manual bibliography is too much work.

**Comment by stefan-mueller** [comment]
Better idea! Should we add a "Quanteda-Based Publications" icon to the five existing ones on the main page using the [book](https://fontawesome.com/icons/book?style=solid) provided by Fontawesome?

**Comment by koheiw** [comment]
We are using book icons for documentation, so https://fontawesome.com/icons/file-alt?style=regular would be better.
